### ISSUE TITLE
Dismissed ssh fs prompts prevent text expansion on macOS

### ISSUE THREAD

**Issue by finn-matti** [SchoofsKelvin/vscode-sshfs#211] opened 2020-08-14 13:19 UTC
It seems to me that when I accidentally dismiss a prompt secure input is not released properly which prevents text expansion (in my case via [Keyboard Maestro](https://www.keyboardmaestro.com/)). [Textexpander](https://smilesoftware.com/textexpander/secureinput/) has a FAQ entry (for users), which might be helpful to understand the issue.

So far the only workaround I'm aware of is to restart the computer.

Info from VS Code

Version: 1.48.0
Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-13T08:03:27.059Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0 (this is macOS Catalina 10.15.6)

Extension Version: 1.18.2

**Comment by SchoofsKelvin** [comment] 2020-08-14 14:48
I assume you're talking about an input prompt VSCode shows, not the Settings UI where you add/edit SSH FS configurations?

Is this actually an issue caused by my extension, or do other extensions that provide password/passphrase inputs also have this problem? For prompting, I _(and any other extension, unless they have a custom editor/webview like my Settings UI)_ have to use the UI API that VSCode provides, so this seems more like an issue on their end.

For the record, I prompt using [VSCode's InputBox](https://github.com/SchoofsKelvin/vscode-sshfs/blob/v1.18.2/src/connect.ts#L100) which handles making it a [secure input](https://github.com/microsoft/vscode/blob/1.48.0/src/vs/vscode.d.ts#L9047) when needed. I also set [ignoreFocusOut](https://github.com/microsoft/vscode/blob/1.48.0/src/vs/vscode.d.ts#L8909) to true, which should prevent the prompts from even being dismissed unless you explicitly close it e.g. pressing ESC.

If it's indeed VSCode's UI you're talking about, you should report this [on their end](https://github.com/microsoft/vscode/issues/new/choose). If this issue happens even for non-secure inputs _(what you enter remains visible)_, you'd probably mention that too. Wasn't very clear from your initial description.

**Comment by finn-matti** [comment] 2020-08-17 07:30
>I assume you're talking about an input prompt VSCode shows, not the Settings UI where you add/edit SSH FS configurations?

Yes, sorry for not describing it better.

My guess is that when the prompt to enter the password stays open for a long time after waking my laptop back up the box doesn't get drawn anymore. But these are all just guesses.

I will try to raise an issue over there and see what might be responsible.

**Comment by SchoofsKelvin** [comment] 2020-08-17 17:36
I'll close this issue for now. Feel free to comment and reopen if there ends up being something I can do.

**Closed by SchoofsKelvin** 2020-08-17 17:36 UTC
Labels: bug, waiting
