### ISSUE TITLE
Couldn't find the requested PuTTY session

### ISSUE THREAD

**Issue by GammaGames** [SchoofsKelvin/vscode-sshfs#3] opened 2018-05-10 23:03 UTC
Hello! I would love to get this to work, but I'm having some difficulties on Windows. I changed the host for the screenshot, but othrewise this is the settings I am trying to use. This is with a fresh install of PuTTY 0.70.

![image](https://user-images.githubusercontent.com/7832163/39898421-d1f8b744-5473-11e8-8daf-91d7d8087310.png)

**Comment by SchoofsKelvin** [comment] 2018-05-11 08:47
Does your PuTTY session have the same host? (as in, the same string, not just an IP the domain resolves to)

Another problem could be that your PuTTY sessions doesn't have `root` set as username. Currently, if the username field is populated, it'll both filter on hostnamd **and** username.

Now I think about it, filtering on username shouldn't be necessary (or even wanted) when a username is given while the PuTTY session has none set. I'll change it that if you give it a username, it'll only filter if the PuTTY session has also manually set a username. As a quick fix, you can change your PuTTY session to use the username `root`.

**Comment by GammaGames** [comment] 2018-05-11 14:11
The name of the saved session is "groot", and I think I got further! Now it says:

![image](https://user-images.githubusercontent.com/7832163/39928550-df505580-54f2-11e8-8800-0b4fa693d5e5.png)

**Comment by SchoofsKelvin** [comment] 2018-05-11 17:01
The SSH library I use (ssh2) tries these authentication methods in this order:
`None -> Password -> Private Key -> Agent`
It'll skip using a password/key if no password/key is given. Since you don't seem to be using Pageant, I assume you're not using a key either?

That error seems to happen if you haven't specified a password nor a private key. It'll try pageant, which you don't have running.

I'm releasing a small patch in a few minutes that'll hopefully help with this issue.

**Comment by GammaGames** [comment] 2018-05-12 20:16
I'll try it out when I get into work on Monday, thank you!

**Comment by GammaGames** [comment] 2018-05-14 18:30
Success! I do have a few questions though:

* The settings page tells me that it matches multiple schemas, so I tried to remove `password: true` and I could no longer connect. I want to keep all the session information in my vsc settings, which schema should I use?
* It makes me enter my password twice. The first time I can enter anything I want (entering a password just changes what the error notification says), but the second time has to be correct. If I'm already connected with one config and connect with another it will only make me enter the password once. Do you know what could be causing this?
* Even though I'm connected, can edit and save files, and the SSH FS panel has a green light next to the connection, the folder in my workspace says "ssh://<name>/ * Can not resolve workspace folder". Just like with the double password prompt, if I connect with a different config the new one doesn't show the `!` next to it. Do you think this is related to the double password?

The config I'm using is 
```
{
    "putty": true,
    "host": "server_name",
    "root": "/var/path",
    "username": "jlieberg",
    "password": true,
    "name": "test"
}
```

All configs I'm using are for the same server, they just have different roots.

**Comment by GammaGames** [comment] 2018-05-14 18:38
Another thing I noticed: when I create a new window (new workspace) a notification that says `Cannot read property 'filter' of undefined` pops up in the corner. It doesn't happen when the extension is uninstalled and it doesn't show my configs in the panel.

**Comment by SchoofsKelvin** [comment] 2018-05-14 18:59
* For the multiple schemas, it's probably because you have `"putty": true` and set a `host`. That's something I should check (and most likely fix) in the schema definition.
* I've never had a problem with it asking for the password twice (well, at least not in a version I published to the marketplace), but I'll take a look.
* I'm not sure what exactly causes that warning. I've had it happen now and then too, where it marks a workspace as broken because it's still connecting.

>Another thing I noticed: when I create a new window (new workspace) a notification that says Cannot read property 'filter' of undefined pops up in the corner.
That sounds like I might be trying to read (and filter) settings that don't exist.

Having these all be separate issues might be handy, but these sound like things that I could fix quite fast.

**Comment by SchoofsKelvin** [comment] 2018-05-14 19:08
The `Cannot read property 'filter' of undefined` bug should be fixed.

>It makes me enter my password twice. The first time I can enter anything I want (entering a password just changes what the error notification says), but the second time has to be correct.

What does the error notification say?

**Comment by GammaGames** [comment] 2018-05-14 20:40
If I leave the field empty:
![image](https://user-images.githubusercontent.com/7832163/40022144-595e6f0e-5784-11e8-81b5-530da0c92f39.png)

If I type gibberish into the password:
![image](https://user-images.githubusercontent.com/7832163/40022187-73eefac8-5784-11e8-83bd-6ffd3e5c9f70.png)

If I type the correct password into the field it just goes away.  
After all three it will ask me again a few seconds later, and then if that is successful it will connect and open the folder.

**Comment by SchoofsKelvin** [comment] 2018-05-16 10:52
I can't seem to reproduce this behavior right now. It looks to me as if creating the first folder triggers extension restarts because the workspaceRoot changes. I'll try some other things to reproduce this later. Right now, I don't really see how I can fix this right now.

**Comment by GammaGames** [comment] 2018-05-16 14:11
I just tried to recreate the error again and it doesn't seem to be happening anymore. I tried both in a new workspace and an existing one ¯\\\_(ツ)_/¯ feel free to close this issue when you want to

**Closed** 2018-05-16 15:05 UTC
Labels: bug
