### ISSUE TITLE
Commands not registered

### ISSUE THREAD

**Issue by PaulPrice** [SchoofsKelvin/vscode-sshfs#37] opened 2018-08-25 15:59 UTC
Having installed SSHFS v1.9.2 under VSCode 1.26.1, I do not have access to any of the SSHFS functionality. For example, I get:

    command 'sshfs.new' not found

Same thing with all the other commands available from the Palette.

This is the same problem as #1, but it's appearing in modern versions of SSHFS and VSCode; and I don't appear to be the only one with this problem.

I hope you will fix this soon, as this looks like exactly the extension I want (support for agent, multiple targets). I'm happy to help debug, but I'm a complete VSCode n00b.

**Comment by PaulPrice** [comment] 2018-08-25 17:11
And now it's magically working.
It's possible that it wasn't loading because of a bad config: I didn't have a `name` element (discovered via the PROBLEMS tab).
Looking at the "Log (Extension Host)" output, I noticed that the extension doesn't get loaded until I open the Command Palette. I'm guessing what's happening is it's attempting to load, finds a bad configuration and only half-loads.

**Comment by SchoofsKelvin** [comment] 2018-09-08 19:51
Duplicate of #1

It seems like this bug happens sometimes to people, but I can't barely reproduce it. Since all commands are properly registered in `activationEvents`, it seems it might be a bug in vscode. I'll later on see if I can reproduce it again somehow.

**Comment by skeetmtp** [comment] 2018-10-12 11:15
Hello, 

I successfully mitigate this bug by : 
* update vscode to 1.28.1 (from 1.25.0)
* manually remove all sshfs settings in User Settings
* restart vscode
* cltr-shift-p "Create a SSH  FS Configuration"

I don't know which step helped, but it finally worked !

**Comment by SchoofsKelvin** [comment] 2018-10-14 13:02
I'm not sure whether updating and removing the settings mattered, or whether restarting vscode was all that was needed.

Closing this issue now, as it's a duplicate, and this still seems something caused by the extension API, not  the actual extension.

**Closed by SchoofsKelvin** 2018-10-14 13:02 UTC
Labels: bug, duplicate
