### ISSUE TITLE
no provider file

### ISSUE THREAD

**Issue by IdoHakimi** [SchoofsKelvin/vscode-sshfs#86] opened 2018-12-17 11:08 UTC
I manage to mount the server and copy files to the server.
However, when I try to copy files from localhost to the server I get: **"no provider for file:///..."**
Any work around this?

I'm using the vscode version 1.3.0 and extension version 1.11.2

**Comment by SchoofsKelvin** [comment] 2019-02-06 20:16
Duplicate of #63

**Closed by SchoofsKelvin** 2019-02-06 20:16 UTC
