### ISSUE TITLE
Dotfiles and dotfolders are hidden

### ISSUE THREAD

**Issue by firelizzard18** [SchoofsKelvin/vscode-sshfs#100] opened 2019-01-28 00:53 UTC
In my ssh root, I have a `.vscode` folder. This folder is not listed. This is an issue.

**Comment by SchoofsKelvin** [comment] 2019-02-06 19:41
Is there perhaps some setting you changed that could hide this? The extension doesn't do any filtering at the moment.

**Comment by firelizzard18** [comment] 2019-02-12 18:28
I'm fairly sure I haven't changed anything. `.vscode` appears normally for my on-disk projects. I'll poke around.

**Comment by DarthSpock** [comment] 2019-02-19 14:02
I see it on my instance on a Fedora 28 server.

**Comment by SchoofsKelvin** [comment] 2019-02-19 20:06
I've just tested on Ubuntu 16, and I could both see `.vscode` and many other dot files, including `.cache`, `.config`, ...

The only thing I couldn't see was directories named `.git` and `.npm`, but I have those in my `files.exclude` in my vscode settings, so that's normal.

Closing this issue for now. If you still have this issue and find a way for me to reproduce it, post it here and reopen the issue.

**Closed by SchoofsKelvin** 2019-02-19 20:06 UTC
Labels: bug, waiting

**Comment by harrv** [comment] 2024-12-10 23:22
Sorry for commenting here almost six years later, but this is where Google brings me. I have some pertinent info to this hidden file issue. I just started using this extension today and ran into this. I found a way to control whether or not hidden files and folders show in the side bar.

Go to VS Code settings and search for `files.exclude`. Note that there are three tabs for User, Workspace, and SSH - FS. In my case, all three have the same list of patterns, except the SSH - FS tab has one additional pattern `.*` that excludes anything starting with a dot. If I remove that pattern then the file listing immediately changes to show things beginning with dot (that don't match one of the other patterns).

![image](https://github.com/user-attachments/assets/17f69cfa-a9ef-4947-b87f-5ecc64a8f3ff)

I don't know whether this is really a pattern that SSH FS added though, because I set up two configs for SSH FS that were identical other than IP address and one of them has this pattern and the other one doesn't. I had previously used Microsoft's Remote SSH extension with that server so it's possible the difference has something to do with that.

Anyway, to anyone else stumbling across this, just use the above setting (adding or removing patterns) to give you control over the files you see and those you don't.
