### ISSUE TITLE
Python completion doesn't work

### ISSUE THREAD

**Issue by gigi206** [SchoofsKelvin/vscode-sshfs#45] opened 2018-09-12 17:16 UTC
Hello,

I tried to open python file and I have only the syntax color that works. Completion, linting, etc.. don't work.

Is there a way for it works ?

**Comment by SchoofsKelvin** [comment] 2018-09-15 17:12
Duplicate of #42

**Closed by SchoofsKelvin** 2018-09-15 17:12 UTC

**Comment by selpoG** [comment] 2018-12-19 12:40
I think the cause of the problem is vscode cannot find remote python.
If you select python version via vscode, `"python.pythonPath"` will be `"home/local_user/.pyenv/shims/python2"`, which should be `"/home/remote_user/.pyenv/shims/python2"`.
If there is any way to tell vscode the correct path of remote python, linter will work properly.

**Comment by jlam17** [comment] 2019-02-12 14:55
Is there a way to hack around this?
