### ISSUE TITLE
Allow this extension the Resource Control??

### ISSUE THREAD

**Issue by developez** [SchoofsKelvin/vscode-sshfs#369] opened 2023-02-27 10:40 UTC
Hello

I cannot use SSH Remote extensión from Microsoft because i have got problems with it (CPU to 100% and other issued), I am triying to use this but the problem is that SSH FS does detect the GIT repository and Source Control does not work.

Is possible??

![image](https://user-images.githubusercontent.com/1931408/221542300-7b1a00f7-af24-467b-8533-31ba69ecbdba.png)

**Comment by SchoofsKelvin** [comment] 2023-03-24 21:26
Duplicate of #31

**Closed by SchoofsKelvin** 2023-03-24 21:26 UTC
Labels: duplicate, enhancement
