### ISSUE TITLE
How to upload?

### ISSUE THREAD

**Issue by 999-Victor** [SchoofsKelvin/vscode-sshfs#181] opened 2019-12-31 10:14 UTC
It is OK with **downloading** `files and directories` **to a remote** file system, but how to **upload** them **to local**? Can't see any interface.

**Comment by WSLUser** [comment] 2020-01-07 20:25
That sounds very confusing but I think I know what you're trying to say. Yes you can drag files to/from your remote workspace. If you're looking for another way of doing this, the remote-ssh extension might be more for you.

**Comment by 999-Victor** [comment] 2020-01-10 08:59
> That sounds very confusing but I think I know what you're trying to say. Yes you can drag files to/from your remote workspace. If you're looking for another way of doing this, the remote-ssh extension might be more for you.

I can't drag a file or a folder **from** remote FS** to local, it doesn't work. It calls a save window, but it doesn't save. I hope I speak clearly now.
If use only Remote-SSH, it trying to use a remote terminal. I like this extention's interface and how it works and I can use my local bash with it, I can't cofigure "remote development" on some computers because of the docker, it not support a 32-architecture systems, but I will confugre it on other computers, thank you.

P.S. sorry my english

**Comment by SchoofsKelvin** [comment] 2020-03-19 15:28
Duplicate of #44

**Closed by SchoofsKelvin** 2020-03-19 15:28 UTC

**Comment by 999-Victor** [comment] 2020-03-19 16:38
@SchoofsKelvin I fink it is possible to add a "upload" button witch call `scp ...`

**Comment by SchoofsKelvin** [comment] 2020-03-29 11:05
It should indeed be possible to create a button which will prompt you for a source and target file/directory, then use the SFTP session to upload everything. As for using commands on the client _(or even host)_, there are too many issues with that _(cross-platform support, scp having to be installed/enabled, ...)_
