### ISSUE TITLE
Mount directory specification

### ISSUE THREAD

**Issue by RobertSellers** [SchoofsKelvin/vscode-sshfs#114] opened 2019-03-08 14:44 UTC
I don't know if this was covered, but my config is remotely mounting the root inside my C:/ drive and it's pulling in a vast number of unwanted edits. Is there a way to specify the local directory?

**Comment by SchoofsKelvin** [comment] 2019-03-09 22:13
What exactly do you mean with mounting the root inside your C:/ drive? SSH is usually for unix systems, which doesn't have the concept of drive letters.

The configs support `"root": "/var/www/or/so"` to specify which remote directory to mount into vscode. But the extension shouldn't be touching your local drives at once, so I'm not sure what the problem is here.

**Comment by RobertSellers** [comment] 2019-03-11 01:39
I am running vscode from windows 10 to a remote ubuntu machine at "root": "/data/something". The root dir is mapped to what seems to be the "c:/" drive. Whenever I connect this workspace on my windows machine I receive the following warning:

> "The git repository at 'c:\' has too many active changes, only a subset of Git features will be enabled."

I seem to have mapped this to my c:/ drive. I also now notice that my C drive has a new /.git drive and is responding to git commands, but not seeing the remote or anything.  Anyway, this is confusing.

**Comment by DarthSpock** [comment] 2019-03-11 14:48
git is auto-fetching c:/ drive but git also fails to read ssh:// paths. There's an issue I opened for it. Basically you can't use git (or a few other features from various extensions) on remote workspaces using this extension.

**Comment by RobertSellers** [comment] 2019-03-11 15:00
Ok, fair enough. It would be nice if that weren't the case, but this extension is still very useful.

**Comment by SchoofsKelvin** [comment] 2019-03-11 19:39
Sadly enough, it's not something I can resolve.

Duplicate of #31 (related to #42)

**Closed by SchoofsKelvin** 2019-03-11 19:39 UTC
Labels: waiting
