### ISSUE TITLE
Couldn't start a terminal for dianli: All configured authentication methods failed

### ISSUE THREAD

**Issue by sakurarain99** [SchoofsKelvin/vscode-sshfs#261] opened 2021-05-27 09:45 UTC
After installing the SSH FS plug-in, an error occurred. The following is my connection configuration:
"sshfs.configs": [
        {
            "name": "power",
            // "group": "create.power",
            "host": "xxx.xx.xxx.130",
            "port": 22,
            "root": "/",
            "username": "root",
            "password": "root123",
            "agent": "$SSH_AUTH_SOCK"
        }
    ],

**Comment by sakurarain99** [comment] 2021-05-27 09:59
What causes this? Is there any solution?

**Comment by SchoofsKelvin** [comment] 2021-05-27 11:39
This issue would be easier to solve with debug logs, so please follow these steps:
- Add `DEBUG_SSH2` to the `sshfs.flags` array in VS Code's User Settings (settings.json)
    e.g. `"sshfs.flags": ["DEBUG_SSH2"]`
- If you already have a connection open, close it completely (or even reload the window)
- Go to `Output > SSH FS` and copy the log from there after replicating your bug
-  While it should censor passwords/passphrases, I recommend checking it for (other) sensitive data first.
    _(especially since `DEBUG_SSH2` activates some internal logging, which is less likely to be censored)_

At first glance, it looks like you're trying to use a password, but also specified `agent`. When an agent is specified and available, the extension will try to (only) use that agent, even if it fails. That's currently a limitation of the underlying `ssh2` library, but might get resolved in the future.

**Comment by sakurarain99** [comment] 2021-05-28 03:24
Where is `output > SSH FS`?

**Comment by sakurarain99** [comment] 2021-05-31 01:46
[DEBUG]   [ssh2(dianli)] DEBUG: Parser: HMAC size:32
[DEBUG]   [ssh2(dianli)] DEBUG: Parser: IN_PACKETDATAVERIFY
[DEBUG]   [ssh2(dianli)] DEBUG: Parser: Verifying MAC
[DEBUG]   [ssh2(dianli)] DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
[DEBUG]   [ssh2(dianli)] DEBUG: Parser: IN_PACKETDATAAFTER, packet: USERAUTH_FAILURE
[DEBUG]   [ssh2(dianli)] DEBUG: Client: none auth failed
[DEBUG]   [ssh2(dianli)] DEBUG: Outgoing: Writing USERAUTH_REQUEST (password)
[DEBUG]   [ssh2(dianli)] DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
[DEBUG]   [ssh2(dianli)] DEBUG: Parser: IN_PACKET
[DEBUG]   [ssh2(dianli)] DEBUG: Parser: Decrypting
[DEBUG]   [ssh2(dianli)] DEBUG: Parser: pktLen:60,padLen:6,remainLen:48
[DEBUG]   [ssh2(dianli)] DEBUG: Parser: IN_PACKETDATA
[DEBUG]   [ssh2(dianli)] DEBUG: Parser: Decrypting
[DEBUG]   [ssh2(dianli)] DEBUG: Parser: HMAC size:32
[DEBUG]   [ssh2(dianli)] DEBUG: Parser: IN_PACKETDATAVERIFY
[DEBUG]   [ssh2(dianli)] DEBUG: Parser: Verifying MAC
[DEBUG]   [ssh2(dianli)] DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
[DEBUG]   [ssh2(dianli)] DEBUG: Parser: IN_PACKETDATAAFTER, packet: USERAUTH_FAILURE
[DEBUG]   [ssh2(dianli)] DEBUG: Client: password auth failed
[DEBUG]   [ssh2(dianli)] DEBUG: Outgoing: Writing USERAUTH_REQUEST (keyboard-interactive)
[DEBUG]   [ssh2(dianli)] DEBUG: Parser: IN_PACKETBEFORE (expecting 16)
[DEBUG]   [ssh2(dianli)] DEBUG: Parser: IN_PACKET
[DEBUG]   [ssh2(dianli)] DEBUG: Parser: Decrypting
[DEBUG]   [ssh2(dianli)] DEBUG: Parser: pktLen:60,padLen:6,remainLen:48
[DEBUG]   [ssh2(dianli)] DEBUG: Parser: IN_PACKETDATA
[DEBUG]   [ssh2(dianli)] DEBUG: Parser: Decrypting
[DEBUG]   [ssh2(dianli)] DEBUG: Parser: HMAC size:32
[DEBUG]   [ssh2(dianli)] DEBUG: Parser: IN_PACKETDATAVERIFY
[DEBUG]   [ssh2(dianli)] DEBUG: Parser: Verifying MAC
[DEBUG]   [ssh2(dianli)] DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)
[DEBUG]   [ssh2(dianli)] DEBUG: Parser: IN_PACKETDATAAFTER, packet: USERAUTH_FAILURE
[DEBUG]   [ssh2(dianli)] DEBUG: Client: keyboard-interactive auth failed
[ERROR]   [createSSH(dianli)] All configured authentication methods failed
Logged at:
	at T.<anonymous> (/home/sakura/.vscode/extensions/kelvin.vscode-sshfs-1.20.1/dist/2.extension.js:1:5991)
	at T.emit (events.js:315:20)
	at F (/home/sakura/.vscode/extensions/kelvin.vscode-sshfs-1.20.1/dist/0.extension.js:1:22077)
	at q (/home/sakura/.vscode/extensions/kelvin.vscode-sshfs-1.20.1/dist/0.extension.js:1:23098)
	at ae.Q (/home/sakura/.vscode/extensions/kelvin.vscode-sshfs-1.20.1/dist/0.extension.js:1:24656)
Reported from createSSH(dianli)
[DEBUG]   [ssh2(dianli)] DEBUG: Outgoing: Writing DISCONNECT (BY_APPLICATION)

**Comment by sakurarain99** [comment] 2021-05-31 01:47
The password can be confirmed

**Comment by SchoofsKelvin** [comment] 2021-05-31 13:43
According to those logs, it does try to log in with the password, but the server replies with a failure. If you're sure the password is correct, I can only think of a few causes:
- You're using a password for the wrong user
- Your server is configured to disallow password authentication (for that user, at least)

You could perhaps take a look at your server's sshd logs _(depending on your OS, these might be in some "security logs" or a journal)_ while potentially even running sshd with `LogLevel` set to `DEBUG3` or similar. Should you share these logs, be sure to thoroughly go through them, as the debug log levels can start logging some very sensitive information.

**Comment by sakurarain99** [comment] 2021-06-01 05:48
Well, thank you

**Closed** 2021-06-01 06:04 UTC
Labels: bug, waiting

**Comment by SchoofsKelvin** [comment] 2021-06-02 13:20
Since you closed the issue, I assume you found the cause and how to fix it?
