### ISSUE TITLE
Allow ssh-agent for authentication (Win32-OpenSSH)

### ISSUE THREAD

**Issue by DennisGaida** [SchoofsKelvin/vscode-sshfs#317] opened 2021-12-20 22:08 UTC
Windows ships in newer versions with OpenSSH OOTB including `ssh-agent` to manage private keys to replace PuTTy pageant.

In the settings I can only configure pageant or a unix socket, which the ssh-agent implementation does not have: https://github.com/PowerShell/Win32-OpenSSH/issues/1761.

Could we get support for the Windows version of ssh-agent nonetheless?

**Comment by SchoofsKelvin** [comment] 2021-12-21 17:14
Duplicate of #83 and #97

OpenSSH port should still expose a "unix socket" (as a named pipe on Windows) which you can make use of, and the Settings UI actually suggests it too:
![Screenshot of Agent field](https://user-images.githubusercontent.com/14597409/146970322-9afd26b7-ce85-41ff-8521-e647b1e9afd2.png)
While I don't remember the exact source where I got that suggestion from, it is mentioned in PowerShell/Win32-OpenSSH#1586. I just did a quick test and using that value does make the extension make use of the OpenSSH agent running in Windows.

**Closed by SchoofsKelvin** 2021-12-21 17:14 UTC

**Comment by DennisGaida** [comment] 2021-12-21 19:31
Sorry for the duplicate! I totally didn’t see the drop down in the extension and just read the explainer text above as well as the readme/wiki here. Should have searched the issues I guess.
