### ISSUE TITLE
Auto Refresh

### ISSUE THREAD

**Issue by N7K5** [SchoofsKelvin/vscode-sshfs#358] opened 2022-10-25 19:02 UTC
The extension automaticly refreshes the open-file tree every time I move the focus of windows (i.e. select another application and come back to vs code). This makes the extension very slow. Please add a setting to disable the auto refresh working-tree on re-focus.

**Comment by SchoofsKelvin** [comment] 2023-03-24 21:59
Duplicate of #360.

The Explorer pane refreshing on window focus is something built-in into and done by VS Code itself. Unless they added an option to disable that, it's not possible to prevent this.

**Closed by SchoofsKelvin** 2023-03-24 21:59 UTC
Labels: duplicate, enhancement
