### ISSUE TITLE
File not found (ssh://connect/)

### ISSUE THREAD

**Issue by ll931217** [SchoofsKelvin/vscode-sshfs#6] opened 2018-05-19 01:25 UTC
Hello,

I am currently using VS Code Portable, I am trying to connect to my home PC with this package, it works when I am not using the portable version. So I want to ask why it could cause this problem and how can I fix it? That error message shows up whenever I connect.

**Comment by SchoofsKelvin** [comment] 2018-05-19 13:10
I've never used VS Code Portable. Do you mean you download the .zip and run it with the extensionPath etc set?

**Comment by ll931217** [comment] 2018-05-20 06:30
No, I downloaded the extension from the extension store/library place in VS Code.

**Comment by SchoofsKelvin** [comment] 2018-05-20 15:20
But where did you download VS Code Portable from? There doesn't seem to be an official portable version, although it seems you can download VS Code as a .zip, unpack and do stuff that way. Is that what you're using?

**Comment by ll931217** [comment] 2018-05-21 02:36
I got VS Code Portable from [here](https://github.com/garethflowers/vscode-portable/releases/tag/Latest)

**Comment by SchoofsKelvin** [comment] 2018-05-21 17:26
I'll download it sometime and see if I can reproduce the bug.

**Comment by Bernix01** [comment] 2018-06-20 18:22
Same problem here on non portable version of VS Code.

**Comment by SchoofsKelvin** [comment] 2018-06-22 12:03
Does the remote folder (the `root` config field) exist on the server?

Does the explorer (after pressing the reload icon) show anything in the workspace folder?

**Comment by Bernix01** [comment] 2018-06-22 12:09
It worked when absolute path was given in `root` config field

**Comment by SchoofsKelvin** [comment] 2018-06-22 12:32
Ah, I'm pretty sure `~` isn't supported, as that's usually "done" by the shell. I might look into detecting the home directory and adding `~/...` support.

**Comment by SchoofsKelvin** [comment] 2018-06-22 16:31
- Using an invalid root directory (or one that can't be read) shows an error now (ea3a5e10)
- Using paths starting with `~` is now supported (c29138a3)

Both new features are published in version 1.8.0 of the extension.

This error might still show up without the "invalid root directory" error, but this seems to be a known issue (Microsoft/vscode#51088). I'll close this issue, but keep an eye on the vscode one.

**Closed by SchoofsKelvin** 2018-06-22 16:31 UTC
