### ISSUE TITLE
Permissions on Created File

### ISSUE THREAD

**Issue by thekendog** [SchoofsKelvin/vscode-sshfs#214] opened 2020-09-03 00:55 UTC
Whenever I create a file it assigns 666 permissions.  It should be 644.

**Comment by thekendog** [comment] 2020-09-03 01:02
Edit: Found the newFileMode setting in another issue on here.  It's not in the GUI settings or documentation.

**Comment by SchoofsKelvin** [comment] 2020-09-04 16:24
Duplicate of #39 

Not a huge priority of adding a Settings UI entry for this, but I'll keep it in mind.

The 666 seems a bit weird. I can't check the code right now, but the default umask shouldn't be that.

**Comment by MostHated** [comment] 2021-11-12 20:21
Due to the fact that I have been making world-writable files left and right for quite some time now and didn't realize it, I think that at a minimum, it should be in the UI as up to right now, it seems the default is still 666.

**Comment by SchoofsKelvin** [comment] 2021-12-03 17:50
Just added this (af76438, b904fb9) to the extension. The default permission is now `0o664` (`rw-rw-r--`), while the UI now also has an easy table-like config field for `newFileMode`:
![Screenshot of new field](https://user-images.githubusercontent.com/14597409/144648920-f2a7d05c-2998-4799-a063-a391a80c67c0.png)

Mind that I stuck with the default for non-root users (`0o664`), even for the root user (where the usual default is `0o644`) as it is difficult to detect the current user within SFTP. Besides that, the terminal is (still) unaffected by `newFileMode`, it only affects files created through the SFTP interface, i.e. by VS Code, such as the Explorer view.

**Closed by SchoofsKelvin** 2021-12-03 17:50 UTC
Labels: enhancement, webview
