### ISSUE TITLE
Does it work with Git repos?

### ISSUE THREAD

**Issue by deurk** [SchoofsKelvin/vscode-sshfs#194] opened 2020-04-18 17:42 UTC
I do not see any of the git activity/tools when a folder mapped to a SSH folder is in my workspace :(

**Comment by mr-eyes** [comment] 2020-04-20 19:07
I think this is a duplicate issue #31

**Comment by SchoofsKelvin** [comment] 2020-07-07 17:19
Duplicate of #31

**Closed by SchoofsKelvin** 2020-07-07 17:19 UTC
