### ISSUE TITLE
[Feature Request] Find in Folder

### ISSUE THREAD

**Issue by playcock** [SchoofsKelvin/vscode-sshfs#190] opened 2020-03-24 15:22 UTC
I would like the ability to use the "Find in Folder" vscode feature with SSH FS. 

Currently, I can find a string in the folder if I have the file open, but I just want to see all files that match the string without having to have the files open in my editor first.
![image](https://user-images.githubusercontent.com/9416592/77443719-a4401400-6dc1-11ea-8229-177e6575a07a.png)

Thank you!

**Comment by SchoofsKelvin** [comment] 2020-03-29 10:46
Duplicate of #2

While I'm still considering implementing a search provider, it would be tricky to make it work for all servers, while also being highly inefficient. I also suggest checking out VSCode's [Remote SSH](https://code.visualstudio.com/docs/remote/ssh).

**Closed by SchoofsKelvin** 2020-03-29 10:46 UTC
