### ISSUE TITLE
Interaction with other extentions (PHP Intelephense, Bookmarks)

### ISSUE THREAD

**Issue by ASMag** [SchoofsKelvin/vscode-sshfs#275] opened 2021-07-14 11:31 UTC
Thanks for writing extention SSH FS!

**Situation**: I would like to use SSH FS to open php files from a server directly without indirection by WinSCP or doing a local copy of the files.

**Issue**: Othe VSC extentions like PHP Intelephense oder Boomarks do not work properly with files, which are opened by SSH FS.
Bookmark extention: Context menue is available. But the blue bookmark symbol left beside the line number is not showed immediately after bookmarking a line. It is showed after switching back from another opened file.
PHP Intelephense extention: "Keine Symbole im Dokument" (German for "no symbols in document"). So no information like names of variables, functions, classes are available in the left bottom corner.

Image shows the described issue:
![SSH FS interaction with Bookmark, PHP Intelephense](https://user-images.githubusercontent.com/15417092/125614708-5ff096e8-cc61-4793-a77b-6bf83f15e86d.png)

Does SSH FS use another kind of viewing files in VSC?

**Comment by SchoofsKelvin** [comment] 2021-07-15 14:13
Duplicate of #27, #31, #42, #45, #106, #157, #272, ...

Basically, extensions need to use the FileSystemProvider system (what this extension uses to provide files inside VS Code), but most extensions only work with files on the local system. Extensions need to be updated to use this new extension API, which not a lot of extensions do. This is especially difficult for intellisense (language-server) extensions that execute a binary (which cna only access local files) which the extension communicates with.

In such cases, using VS Code's [Remote SSH](https://code.visualstudio.com/docs/remote/ssh) feature is better.

**Closed by SchoofsKelvin** 2021-07-15 14:13 UTC
