### ISSUE TITLE
Support for GSSAPI authentication

### ISSUE THREAD

**Issue by quentinmit** [SchoofsKelvin/vscode-sshfs#230] opened 2020-12-22 08:28 UTC
Unfortunately, the SSH FS extension doesn't seem to pick up GSSAPI as an authentication option even though it's enabled in my `.ssh/config`. This is the settings:

```
GSSAPIAuthentication yes
GSSAPIKeyExchange yes
```

(Note that not all builds of OpenSSH support GSSAPIKeyExchange; it's not in upstream OpenSSH but most Linux distros have it. It's not necessary for GSSAPI authentication to work, but it allows the "trust this key?" prompt to be bypasses on first connection.)

**Comment by SchoofsKelvin** [comment] 2020-12-22 14:28
Duplicate of #24

**Closed by SchoofsKelvin** 2020-12-22 14:28 UTC
