### ISSUE TITLE
Mac M1 - Electron process high CPU

### ISSUE THREAD

**Issue by tamet83** [SchoofsKelvin/vscode-sshfs#329] opened 2022-03-12 21:13 UTC
Hi,

I don't know why but when I use this plugin on my mac book air m1 I noticed that the electron process uses over the 100% of the CPU.

What kind of information can I give you to debug this behavior?

Thanks

**Comment by SchoofsKelvin** [comment] 2022-03-18 21:17
- Which version of VS Code are you using?
- Did this start happening recently since an update, or have you never used the plugin before?
- When exactly does this happen? The moment you start a SSH FS connection? And if so, only at the beginning? When opening/saving files? ...

**Comment by tamet83** [comment] 2022-03-21 20:18
Hello,

sorry for the delay.
1. I'm using VS Cose V. 1.65.2 (Universal)
2. I installed the plugin lately, a month ago if I remember well.
3. The problem happens immediately after I start a SSH session and remain active even if I quit VSC. I need to kill the process manually.

Here a screenshot:

<img width="882" alt="Schermata 2022-03-21 alle 21 09 50" src="https://user-images.githubusercontent.com/7949570/159355580-05f98772-c7fd-43bd-a826-5e1082a7835b.png">

The CPU usage increases more and more after time as you can see:

<img width="884" alt="Schermata 2022-03-21 alle 21 12 47" src="https://user-images.githubusercontent.com/7949570/159355963-074db8bb-2dc6-4f19-80f6-881c06005f01.png">

Whereas here the process info:

```
cwd
/
txt
/Applications/Visual Studio Code.app/Contents/MacOS/Electron
txt
/Applications/Visual Studio Code.app/Contents/Frameworks/Squirrel.framework/Versions/A/Squirrel
txt
/Applications/Visual Studio Code.app/Contents/Frameworks/Mantle.framework/Versions/A/Mantle
txt
/Library/Preferences/Logging/.plist-cache.4lhffmxv
txt
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/v8_context_snapshot.arm64.bin
txt
/Users/matteo/.vscode/extensions/keesschollaart.vscode-home-assistant-1.26.0/node_modules/bufferutil/prebuilds/darwin-x64+arm64/node.napi.node
txt
/Applications/Visual Studio Code.app/Contents/Frameworks/ReactiveObjC.framework/Versions/A/ReactiveObjC
txt
/Users/matteo/.vscode/extensions/keesschollaart.vscode-home-assistant-1.26.0/node_modules/utf-8-validate/prebuilds/darwin-x64+arm64/node.napi.node
txt
/usr/lib/dyld
txt
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libffmpeg.dylib
txt
/usr/share/icu/icudt68l.dat
txt
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/icudtl.dat
txt
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
0
->0x4a1a107e1ad1e27
1
->0x4a1a107e1ad1fb7
2
->0x4a1a107e1ad2147
3
->0x4a1a107e1ad22d7
4
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/icudtl.dat
5
count=2, state=0x8
6
->0x1a55649e91ea665f
7
->0xb9842e3b614aff4f
8
->0xeefacd677c5ea242
9
->0xc4ee38849a90bb92
10
->0xb548269e42e765ca
11
->0x69cea77e0ea0749e
12
/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/v8_context_snapshot.arm64.bin
13
count=0, state=0
14
->0x729e5cd626dda921
15
->0x13559512ccb46e35
16
->0x203269762bf4fecb
17
->0x3d92afbca2d874e3
18
count=0, state=0x12
19
count=0, state=0xa
20
->0x80b537d6e104d5f0
21
->0x97eed112b854ee21
22
->0x2f12c90be685e4c7
23
->0xb91df9bb0ba043c8
24
/dev/null
```

Let me know if you need other info and thanks for your help.

**Comment by SchoofsKelvin** [comment] 2022-03-22 21:28
I don't know if you have access to the output pane when VS Code is frozen (I assume the extension host process is frozen, not the UI), but if possible:
- Add `DEBUG_SSH2` to the `sshfs.flags` array in VS Code's User Settings (settings.json)
    e.g. `"sshfs.flags": ["DEBUG_SSH2"]`
    - See [this issue](https://github.com/SchoofsKelvin/vscode-sshfs/issues/270) for more information about adding flags
- If you already have a connection open, close it completely (or even reload the window)
- Go to `Output > SSH FS` and copy the log from there after replicating your bug
-  While it should censor passwords/passphrases, I recommend checking it for (other) sensitive data first.
    _(especially since `DEBUG_SSH2` activates some internal logging, which is less likely to be censored)_

Some more questions to help me figure out the cause:
- What OS and version of OpenSSH (or similar) is your server running?
- Do you have any special OpenSSH server settings?
- Have you tried other servers? If so, does this issue also happen there?

**Comment by tamet83** [comment] 2022-03-25 23:46
Hi,

I think the problem is with VSC, i'm not the only one as you can see [here](https://github.com/microsoft/vscode/issues/142828).
I tried to open an issue on [VSC official github page](https://github.com/microsoft/vscode/issues/146090)

**Comment by SchoofsKelvin** [comment] 2022-03-26 21:43
It looks like they did some upgrades and reverts regarding Electron between 1.64 and 1.65.2 which I assume lead to the issue. Something similar happened in #239 where an Electron upgrade resulted in certain algorithms crashing the extension host when used. Since the high CPU usage in your case only happens when you start a SSH connections, it might be something very similar. You can actually try adding the `DF-GE` and see if that fixes it. Very low chance, but it might.

I'll be closing this ticket for now. If something changes and it looks like the extension's fault again, or there's a quick fix I can implement (e.g. disabling certain ciphers/algorithms), feel free to comment and reopen this ticket.

**Closed by SchoofsKelvin** 2022-03-26 21:43 UTC
Labels: bug, waiting

**Comment by tamet83** [comment] 2022-03-30 18:30
Hello, we find out what's causing this issue.
Right now the problem isn't solved, I had to disable the addon.
I leave the links for future reference.

- Here the the hint from [vsc github](https://github.com/microsoft/vscode/issues/146090)
- Here the issue opened on the [addon](https://github.com/keesschollaart81/vscode-home-assistant/issues/2008) maintainer causing the problem
