### ISSUE TITLE
Have a remote fs recognized as a git repo (or perforce, etc)

### ISSUE THREAD

**Issue by davidritter** [SchoofsKelvin/vscode-sshfs#127] opened 2019-04-10 14:36 UTC
This is an awesome extension. The only problem I still have is my connected FS is finding and rendering my repo and all files/folders EXCEPT .git and the repo isn't being recognized by the git plugin.

Is there something special I need to do to enable this?

Thanks!
Dave

**Comment by SchoofsKelvin** [comment] 2019-04-12 14:25
Duplicate of #31

**Closed by SchoofsKelvin** 2019-04-12 14:25 UTC
