### ISSUE TITLE
PyLint not working

### ISSUE THREAD

**Issue by drdee255** [SchoofsKelvin/vscode-sshfs#106] opened 2019-02-14 07:37 UTC
When I try to write python code its doesn't show any suggestions. I think pylint is not working

**Comment by DarthSpock** [comment] 2019-02-19 13:57
Linting appears to work for me ( I get suggestions, code snippets, etc. though I also have IntelliCode). It's just debug and tests such as through `pytest` that fail.

**Comment by SchoofsKelvin** [comment] 2019-02-19 20:12
Duplicate of #42

Basically, extensions can't work with FileSystemProviders (the system behind "remote filesystems inside vscode") yet, so extensions only work with files on the local system. Even after vscode added an extension API for properly accessing (remote) files, it might still take a while for extensions themselves to update.

**Closed by SchoofsKelvin** 2019-02-19 20:12 UTC
