### ISSUE TITLE
eslint not working?

### ISSUE THREAD

**Issue by webdeveloperpr** [SchoofsKelvin/vscode-sshfs#113] opened 2019-03-04 20:15 UTC
For some reason when I use this plugin eslint does not work? Is there anything one has to do to get this working?

**Comment by kr094** [comment] 2019-03-07 17:47
It looks like most of vs codes features are neutered when using this plugin. Using the format document command I get "There is no document formatter for javascript- installed". I've tried both eslint and prettier. If you highlight a selection and look in the context menu, most of the options are gone from remote editors. 
FWIW the ssh-fs works like a dream as far as syncing changes back to the server, but it leaves a lot to be desired to fully integrate with vs code.

**Comment by SchoofsKelvin** [comment] 2019-03-09 22:09
Duplicate of #78 (more info in #42)

Short recap: Extensions right now only work with local files, as VSCode doesn't currently have an API for extensions to interact with remote files provided by other extensions. Also, once that does get added, it still takes a while before extensions make use of it. Not to mention that some extensions (like the built-in Git extension) use binaries that only work on local filesystems.

**Closed by SchoofsKelvin** 2019-03-09 22:09 UTC
