### ISSUE TITLE
Unable to load schema errors

### ISSUE THREAD

**Issue by Elektrolott** [SchoofsKelvin/vscode-sshfs#34] opened 2018-08-23 07:32 UTC
Hi,

as I am behind a proxy (for external sites - and some may be blocked even then) I get an error:

> Problems loading reference 'https://raw.githubusercontent.com/SchoofsKelvin/vscode-sshfs/27dec3277d9a50869c3d2a11db21da6e07a3223a/settingsschema.json': Unable to load schema from 'https://raw.githubusercontent.com/SchoofsKelvin/vscode-sshfs/27dec3277d9a50869c3d2a11db21da6e07a3223a/settingsschema.json': Unable to connect to https://raw.githubusercontent.com/SchoofsKelvin/vscode-sshfs/27dec3277d9a50869c3d2a11db21da6e07a3223a/settingsschema.json. Error: getaddrinfo ENOTFOUND raw.githubusercontent.com raw.githubusercontent.com:443

Could you package that schema together with the extension, so that no external access is needed?

**Comment by klauern** [comment] 2018-09-07 13:14
I think this is a more global issue, as I had this happen outside of this extension. I  just installed this extension today and I've seen this kind of error before.  I, too, work behind a proxy, but I haven't figured out which extension is generating this error.

**Comment by SchoofsKelvin** [comment] 2018-09-08 20:42
Duplicate of #40 *(well, I saw this one afterwards because of the order I went through my notifications)

But yes, unless big problems pop up, I'll combine every schema and include it in the extension manifest, so no web calls are needed.

**Closed** 2018-09-25 16:58 UTC
Labels: bug, duplicate
