### ISSUE TITLE
C/C++ IntelliSense auto-completions don't work with files accessed via SSH-FS

### ISSUE THREAD

**Issue by george-somerville-ma** [SchoofsKelvin/vscode-sshfs#157] opened 2019-06-28 00:54 UTC
C/C++ IntelliSense auto-completions don't work with files accessed via SSH-FS, though the auto-completions do work with local files.

**Comment by SchoofsKelvin** [comment] 2019-07-03 16:05
Duplicate of #27

**Closed by SchoofsKelvin** 2019-07-03 16:05 UTC
