### ISSUE TITLE
Run VS Code with admin privileges so the changes can be applied.

### ISSUE THREAD

**Issue by fakhamatia** [SchoofsKelvin/vscode-sshfs#131] opened 2019-04-22 20:33 UTC
Every time i use ssh extension VSCode show this

"Run VS Code with admin privileges so the changes can be applied."

Its OK? because extension work OK but i cant remove file or folder but i can rename

**Comment by SchoofsKelvin** [comment] 2019-04-23 12:01
That's weird. The extension doesn't require any admin privileges, nor does it request any. What OS and VSCode/extension version are you on?

**Comment by fakhamatia** [comment] 2019-04-23 12:24
VSCode > 1.33.2
Extension > 1.16.1
Ubuntu 18.04 > Client
Ubuntu 16.04 > Server
Remote Folder /var/www/html

**Comment by SchoofsKelvin** [comment] 2019-04-23 13:53
A quick google search indicates it is probably another extension:
- be5invis/vscode-custom-css#18
- Microsoft/vscode-go#1199

Try disabling other extensions and see if that message still appears.

**Comment by fakhamatia** [comment] 2019-04-23 15:04
I disable vscode-custom-css and message didn't show.
That is weird, before i use ssh extension message didn't show , but when click connect error will appear.
whats the connection?

**Comment by SchoofsKelvin** [comment] 2019-04-23 18:10
When you remote your ssh fs, it opens `ssh://sharif-camera/` as WorkspaceFolder. The extension probably assumes every WorkspaceFolder is on the local drive, and tries to access `/sharif-camera` *(or something like `/sharif-camera/some-css-extension-file.ext`)*. That directory doesn't exist, so the OS throws a Permission Denied error or something, which is what the extension thinks is the problem.

Since the problem isn't caused by this extension, I'll be closing this issue. You should probably report this issue to the developers of the vscode-custom-css extension if you want this to get fixed.

**Closed by SchoofsKelvin** 2019-04-23 18:10 UTC
Labels: bug, waiting
