### ISSUE TITLE
SSH key support: ED25519

### ISSUE THREAD

**Issue by RixzZ** [SchoofsKelvin/vscode-sshfs#36] opened 2018-08-25 14:03 UTC
Hello.

I'm trying to use an ED25519 key to mount the workspace folder, but I'm receiving this error:

> Error while connecting to SSH FS scripts-bash: Cannot parse privateKey: Unsupported key format

It seems like this key format is not compatible right now. Can that be added since is completely compatible with current OpenSSH versions (6.5+)?

Thanks!

**Comment by tibibok** [comment] 2018-09-03 09:35
+1

**Comment by rabalyn** [comment] 2018-09-05 14:44
+1

**Comment by l0rda** [comment] 2018-09-07 02:58
+1

**Comment by SchoofsKelvin** [comment] 2018-09-08 20:40
I've looked a tiny bit into it and found this: mscdex/ssh2-streams#100

When I have more time, I'll look into having the extension automatically convert it to a supported format, but this won't be implemented anytime soon.

**Comment by spkane** [comment] 2019-02-07 05:41
I did not see/notice the `Unsupported key format` error so this took me longer to troubleshoot, but in my `sshd` logs I saw this pattern:

```
mobbox-debug_1  | debug1: trying public key file /home/skane/.ssh/authorized_keys
mobbox-debug_1  | debug1: fd 4 clearing O_NONBLOCK
mobbox-debug_1  | debug2: user_key_allowed: check options: 'ssh-ed25519 ...REDACTED... skane@skane-mbpro
mobbox-debug_1  | '
mobbox-debug_1  | debug2: user_key_allowed: advance: '...REDACTED... skane@skane-mbpro
mobbox-debug_1  | '
mobbox-debug_1  | debug2: key not found
```

Switching to my RSA key, worked around this issue, but is not ideal.

Even without a true fix, it would be nice if the plugin reported a proper error via the vscode GUI, so that users don't potentially spend hours trying to figure it out what the problem is.

**Comment by SchoofsKelvin** [comment] 2019-02-25 19:37
If I'm not wrong, this should be the same key format I recently added support for (#85)

**Comment by MrOnosa** [comment] 2019-02-25 20:17
Negative.
![image](https://user-images.githubusercontent.com/2931245/53365971-1b2d8380-3908-11e9-843e-f2c3329534dc.png)

**Comment by SchoofsKelvin** [comment] 2019-02-26 08:04
Ah, seems like it's back to waiting on mscdex/ssh2-streams#100:
> FWIW `ssh2-streams` v0.3.0 now supports the "new" OpenSSH key format, but not ed25519 keys yet as that requires OpenSSL 1.1.1 which has not yet been incorporated into node core.

**Comment by MrOnosa** [comment] 2019-02-26 13:44
@SchoofsKelvin I would appreciate it if this issue was reopened. Since this is not an issue I created, and because I am not a collaborator, I cannot re-open it myself.

**Comment by SchoofsKelvin** [comment] 2019-02-26 19:22
I'll reopen the issue, but as stated, it's just waiting until ssh2-streams adds support, at which point I'll upgrade that dependency to include the new support.

**Comment by aaronwolen** [comment] 2019-04-29 13:50
Looks like ED25519 support was added last week: https://github.com/mscdex/ssh2-streams/issues/100#issuecomment-486511120

**Comment by SchoofsKelvin** [comment] 2019-04-29 15:20
As the comment indicates, the current version 10.x of node doesn't support it yet.

After a bit of googling, it seems that [10.x will get OpenSSL 1.1.1 soon](https://developer.ibm.com/blogs/openssl-111-has-landed-in-nodejs-master-and-why-its-important-for-nodejs-lts-releases/), but mind that we need to wait on VSCode to update their Electron dependency (Microsoft/vscode#61787), since they use Electron's node version. That would be [Electron 5.0.0](https://electronjs.org/releases/stable#release-notes-for-v500) (unless they release a new 4.x version with a higher 10.x node version, once available), a major version change, while VSCode still uses 3.1.6.

**Summary**: The underlying ssh2 library now supports it, and updating this dependency to the required version isn't a problem, but VSCode won't support it anytime soon yet.

**Comment by fridtjof** [comment] 2019-11-08 12:05
VS Code 1.40, released today, now uses Electron 6: https://code.visualstudio.com/updates/v1_40#_electron-60-update

Seems like the only thing left is to update to ssh2 0.8.3 or higher (latest is 0.8.6).

**Comment by Keridos** [comment] 2020-03-02 00:02
Any updates on this?

**Closed** 2020-03-19 14:58 UTC
Labels: enhancement
